CREATE TABLE CMEMBER(
	MID VARCHAR(20) PRIMARY KEY,
	MPW VARCHAR(20) NOT NULL,
	MNAME VARCHAR(10) NOT NULL,
	MNICKNAME VARCHAR(20) NOT NULL,
	MADD VARCHAR(200) NOT NULL,
	MPHONE VARCHAR(20) NOT NULL,
	MEMAIL VARCHAR(100) NOT NULL
);

DROP TABLE CMEMBER;

SELECT * FROM USER_TABLES;