CREATE TABLE CREPLY(
	RID INT PRIMARY KEY,
	MID VARCHAR(10) NOT NULL,
	BNUM INT NOT NULL,
	CMSG VARCHAR(500) NOT NULL,
	CONSTRAINT CBOARD_CREPLY FOREIGN KEY(BNUM) REFERENCES CBOARD(BNUM) ON DELETE CASCADE
);

DROP TABLE CREPLY;