CREATE TABLE CMEMBER(
	MID VARCHAR(20) PRIMARY KEY,
	MPW VARCHAR(20) DEFAULT 0,
	MNAME VARCHAR(10) NOT NULL,
	MNICKNAME VARCHAR(20) NOT NULL,
	MADD VARCHAR(200) DEFAULT 0,
	MPHONE VARCHAR(20) DEFAULT 0,
	MEMAIL VARCHAR(100) NOT NULL
);
INSERT INTO CMEMBER (MID,MNAME,MNICKNAME,MEMAIL) VALUES('ADMIN','LEE','AD','ADMIN@NAVER,COM')
DROP TABLE CMEMBER;

SELECT * FROM USER_TABLES;
SELECT * FROM CMEMBER;
SELECT MID FROM CMEMBER;
